### PR TITLE
Kitd patch 1

### PR DESCRIPTION
**Pull request by kitd**

### CODE REVIEW

**Comment by jzwolak** [comment]
Hi @kitd , I'm curious why you closed the pull request before I had a chance to review it. I appreciate that you submitted changes and value your feedback and contributions. Also, SwingBuilder is being actively used in a production project of mine. I never finished implementing all of the Java Swing components and properties. I just add the ones I use as I go along, but I find the more declarative style of programming much easier to work with and the structure of the code matches the structure of the UI much more closely.

I have since wrote another library called Retroact that does what I intended SwingBuilder to do. Retroact succeeds where SwingBuilder did not and I also use Retroact in a production project. They both have their place, but most of my development effort will be on Retroact.

**Comment by kitd** [comment]
Hi @jzwolak . Sorry for the confusion. I opened the pr on your repo by accident.  I meant to open it on my own fork.

I am researching Swing builder-type libraries, in particular those that can be built using [jbang](https://www.jbang.dev/). Your library came up in my search but there were a few changes needed to work with jbang. Since there is no published Maven package for it, jbang sends this repo to jitpack to be compiled but that currently fails. A java release version is required in build.gradle and some warnings need suppressing. I am still investigating,  but when I am done  I'll submit a proper pr if you like. 

I will also look at Retroact though. Thanks for letting me know!

**Comment by jzwolak** [comment]
SwingBuilder has published maven packages. Are you referring to SwingBuilder when you say “Since there is no published Maven package for it”?

--
Jason Zwolak

**Comment by jzwolak** [comment]
SwingBuilder was my first published Maven package and I went through a lot of trouble to publish it. :-)

--
Jason Zwolak

**Comment by kitd** [comment]
Ok, apologies. It wasn't mentioned on the home page so I assumed it hadn't. That makes things much easier. I don't need the PR in that case as JBang works easily with Maven central.

**Comment by jzwolak** [comment]
At the very top of the README you’ll see a “Maven Central” link. I used the standard way to link to the maven artifact. Though I do see that the link is broken. Perhaps something has changed in the way those links work.

You are right that I don’t mention the maven artifact in the text like most projects do.

--
Jason Zwolak

**Comment by jzwolak** [comment]
Hi Kit,

I updated the docs and the Maven Central link.

Thanks for pointing this out.

Feel free to reach out with questions, suggestions, or PRs. I really appreciate the feedback.

Jason

--
Jason Zwolak

**Pull request closed without merging**
